// Generated by unRap v1.06 by Kegetys

class RscButton {
	idc = -1;
	type = CT_BUTTON;
	text = "";
	style = 0x02 + 0x100;
	x = 0;
	y = 0;
	w = 0.1;
	h = 0.035;
	font = "PuristaMedium";
	sizeEx = 0.025;
	colorText[] = {1,1,1, 1.0};
	colorDisabled[] = {0.4, 0.4, 0.4, 1};
	colorBackground[] = {0.5, 0.5, 0.5, 1};
	colorBackgroundActive[] = {0.6, 0.6, 0.7, 1};
	colorBackgroundDisabled[] = {0.95, 0.95, 0.95, 1};
	offsetX = 0.000;
	offsetY = 0.000;
	offsetPressedX = 0.000;
	offsetPressedY = 0.000;
	colorFocused[] = {0.9, 0.9, 1, 1};
	colorShadow[] = {0.023529, 0, 0.0313725, 1};
	colorBorder[] = {0.023529, 0, 0.0313725, 1};
	borderSize = 0.0;
	soundEnter[] = {"\a3\ui_f\data\sound\RscButton\soundEnter", 0.1, 1};
	soundPush[] = {"\a3\ui_f\data\sound\RscButton\soundPush", 0.1, 1};
	soundClick[] = {"\a3\ui_f\data\sound\RscButton\soundClick", 0.1, 1};
	soundEscape[] = {"\a3\ui_f\data\sound\RscButton\soundEscape", 0.1, 1};
};
