// Generated by unRap v1.06 by Kegetys

class RscCombo
{
	type = CT_COMBO;
	text = "";
	style = 0;
	x = 0;
	y = 0;
	w = 0.12;
	h = 0.035;
	colorSelect[] = { 0.023529, 0, 0.0313725, 1 };
	colorText[] = { 0.023529, 0, 0.0313725, 1 };
	colorBackground[] = { 0.65, 0.65, 0.65, 1 };
	colorSelectBackground[] = { 0.543, 0.5742, 0.4102, 1.0 };
	colorScrollbar[] = { 0.023529, 0, 0.0313725, 1 };
	arrowEmpty = "a3\ui_f\data\gui\cfg\Slider\arrowempty_ca.paa";
	arrowFull = "a3\ui_f\data\gui\cfg\Slider\arrowfull_ca.paa";

	wholeHeight = 0.45;
	color[] = { 0, 0, 0, 0.6 };
	colorActive[] = { 0, 0, 0, 1 };
	colorDisabled[] = { 0, 0, 0, 0.3 };
	font = "PuristaMedium";
	sizeEx = 0.025;

	maxHistoryDelay = 0.1;
	autoScrollSpeed = -1;
	autoScrollDelay = 5;
	autoScrollRewind = 0;

	class ComboScrollBar
	{
		color[] = { 1, 1, 1, 0.6 };
		colorActive[] = { 1, 1, 1, 1 };
		colorDisabled[] = { 1, 1, 1, 0.3 };

		autoScrollEnabled = 1;
		autoScrollSpeed = -1;
		autoScrollDelay = 5;
		autoScrollRewind = 0;

		thumb = "a3\ui_f\data\gui\cfg\Scrollbar\thumb_ca.paa";
		arrowFull = "a3\ui_f\data\gui\cfg\Scrollbar\arrowfull_ca.paa";
		arrowEmpty = "a3\ui_f\data\gui\cfg\Scrollbar\arrowempty_ca.paa";
		border = "a3\ui_f\data\gui\cfg\Scrollbar\border_ca.paa";
	};

	soundSelect[] = { "\a3\ui_f\data\sound\RscCombo\soundSelect", 0.1, 1 };
	soundExpand[] = { "\a3\ui_f\data\sound\RscCombo\soundExpand", 0.1, 1 };
	soundCollapse[] = { "\a3\ui_f\data\sound\RscCombo\soundCollapse", 0.1, 1 };
};
