// Generated by unRap v1.06 by Kegetys

class RscListBox
{
	type = 5;
	style = 16;
	font = "PuristaMedium";
	sizeEx = 0.025;
	rowHeight = 0.0252;
	color[] = { 1, 1, 1, 1 };
	colorText[] = { 0.543, 0.5742, 0.4102, 1.0 };
	colorDisabled[] = { 1, 1, 1, 1 };
	colorScrollbar[] = { 0.95, 0.95, 0.95, 1 };
	colorSelect[] = { 0.95, 0.95, 0.95, 1 };
	colorSelect2[] = { 0.95, 0.95, 0.95, 1 };
	colorSelectBackground[] = { 0, 0, 0, 1 };
	colorSelectBackground2[] = { 0.543, 0.5742, 0.4102, 1.0 };
	soundSelect[] = { "\a3\ui_f\data\sound\RscListBox\soundSelect", 0.1, 1 };
	period = 1.2;
	colorBackground[] = { 0, 0, 0, 1 };

	colorPicture[] = {1, 1, 1, 1};
	colorPictureSelected[] = {1, 1, 1, 1};
	colorPictureDisabled[] = {1, 1, 1, 1};

	maxHistoryDelay = 1.0;
	autoScrollSpeed = -1;
	autoScrollDelay = 5;
	autoScrollRewind = 0;

	class ListScrollBar
	{
		color[] = { 1, 1, 1, 0.6 };

		autoScrollEnabled = 1;
		autoScrollSpeed = -1;
		autoScrollDelay = 5;
		autoScrollRewind = 0;

		colorActive[] = { 1, 1, 1, 1 };
		colorDisabled[] = { 1, 1, 1, 0.3 };
		thumb = "a3\ui_f\data\gui\cfg\Scrollbar\thumb_ca.paa";
		arrowFull = "a3\ui_f\data\gui\cfg\Scrollbar\arrowfull_ca.paa";
		arrowEmpty = "a3\ui_f\data\gui\cfg\Scrollbar\arrowempty_ca.paa";
		border = "a3\ui_f\data\gui\cfg\Scrollbar\border_ca.paa";
	};
};
