// Generated by unRap v1.06 by Kegetys

class RscPicture
{
	type = CT_STATIC;
	idc = -1;
	style = 0x30 + 0x100;
	sizeEx = 0.025;

	colorText[] = { 1, 1, 1, 1 };
	colorBackground[] = { 0, 0, 0, 0 };

	x = 0;
	y = 0;
	w = 1.0;
	h = 1.0;

	font = FontM;
	text = "";

};
